export const RARITY = {
  legendary: { id: 'legendary', label: 'Legendary', color: '#fbbf24', glow: 'rgba(251,191,36,0.45)' },
  epic:      { id: 'epic',      label: 'Epic',      color: '#a78bfa', glow: 'rgba(167,139,250,0.40)' },
  rare:      { id: 'rare',      label: 'Rare',      color: '#60a5fa', glow: 'rgba(96,165,250,0.35)'  },
  common:    { id: 'common',    label: 'Common',    color: '#9ca3af', glow: 'rgba(156,163,175,0.20)' },
}

export const ACHIEVEMENTS = {
  godfather: {
    id: 'godfather',
    rarity: 'legendary',
    icon: 'fa-crown',
    label: 'Godfather',
    labelTH: 'เจ้าพ่อ',
    desc: 'Commands every room without lifting a finger. The undisputed boss.',
    descTH: 'เจ้าพ่อแห่งค่ำคืน ผู้ที่ทุกคนต้องก้มหัวให้',
    color: '#c62419',
    bg: 'rgba(198,36,25,0.14)',
    border: 'rgba(198,36,25,0.35)',
  },
  champion: {
    id: 'champion',
    rarity: 'legendary',
    icon: 'fa-trophy',
    label: 'Champion',
    labelTH: 'แชมเปี้ยน',
    desc: 'Stood victorious when all others fell. The ultimate Script Murder winner.',
    descTH: 'ยืนหยัดเป็นผู้ชนะเมื่อทุกคนล้มลง แชมเปี้ยนที่แท้จริง',
    color: '#fbbf24',
    bg: 'rgba(251,191,36,0.12)',
    border: 'rgba(251,191,36,0.30)',
  },
  villain: {
    id: 'villain',
    rarity: 'epic',
    icon: 'fa-user-secret',
    label: 'Villain',
    labelTH: 'มือสังหาร',
    desc: 'Wore the mask of the murderer and played the role flawlessly.',
    descTH: 'สวมหน้ากากฆาตกรและเล่นบทได้อย่างสมบูรณ์แบบ',
    color: '#f472b6',
    bg: 'rgba(244,114,182,0.12)',
    border: 'rgba(244,114,182,0.30)',
  },
  detective: {
    id: 'detective',
    rarity: 'epic',
    icon: 'fa-magnifying-glass',
    label: 'Detective',
    labelTH: 'นักสืบ',
    desc: 'Cut through every lie to expose the truth. The sharpest mind in the room.',
    descTH: 'ตัดผ่านคำโกหกทุกชั้นเพื่อค้นหาความจริง สมองที่คมที่สุดในห้อง',
    color: '#60a5fa',
    bg: 'rgba(96,165,250,0.12)',
    border: 'rgba(96,165,250,0.30)',
  },
  veteran: {
    id: 'veteran',
    rarity: 'epic',
    icon: 'fa-medal',
    label: 'Veteran',
    labelTH: 'ผู้เล่นเก่าแก่',
    desc: 'A seasoned player who has seen it all — no script can surprise them now.',
    descTH: 'นักเล่นผู้เชี่ยวชาญที่ผ่านมาทุกอย่าง ไม่มีสคริปต์ไหนทำให้แปลกใจได้อีก',
    color: '#a78bfa',
    bg: 'rgba(167,139,250,0.12)',
    border: 'rgba(167,139,250,0.30)',
  },
  golden: {
    id: 'golden',
    rarity: 'rare',
    icon: 'fa-star',
    label: 'Golden Player',
    labelTH: 'ผู้เล่นระดับ Gold',
    desc: 'A top-tier regular — reliably brilliant, every single session.',
    descTH: 'สมาชิกระดับสูงที่มาสม่ำเสมอ เก่งทุกครั้งไม่เคยพลาด',
    color: '#C9A227',
    bg: 'rgba(201,162,39,0.12)',
    border: 'rgba(201,162,39,0.30)',
  },
  explorer: {
    id: 'explorer',
    rarity: 'rare',
    icon: 'fa-compass',
    label: 'Explorer',
    labelTH: 'นักสำรวจ',
    desc: 'Never plays the same script twice. Always seeking the unknown.',
    descTH: 'ไม่เคยเล่นสคริปต์เดิมสองครั้ง มุ่งค้นหาสิ่งที่ยังไม่รู้',
    color: '#34d399',
    bg: 'rgba(52,211,153,0.12)',
    border: 'rgba(52,211,153,0.30)',
  },
  billionaire: {
    id: 'billionaire',
    rarity: 'rare',
    icon: 'fa-money-bill-wave',
    label: 'The Billionaire',
    labelTH: 'มหาเศรษฐี',
    desc: 'Rolls in like they own the place. The big spender of the night.',
    descTH: 'มาถึงเหมือนเป็นเจ้าของ ใช้เงินไม่อั้นทุกคืน',
    color: '#16A34A',
    bg: 'rgba(22,163,74,0.12)',
    border: 'rgba(22,163,74,0.30)',
  },
  hunger: {
    id: 'hunger',
    rarity: 'rare',
    icon: 'fa-utensils',
    label: 'The Hunger',
    labelTH: 'นักกิน',
    desc: 'Always first to suggest a snack break. Food is brain fuel.',
    descTH: 'คนแรกที่เสนอพักกินข้าวเสมอ อาหารคือพลังงานของสมอง',
    color: '#F97316',
    bg: 'rgba(249,115,22,0.12)',
    border: 'rgba(249,115,22,0.30)',
  },
  silver: {
    id: 'silver',
    rarity: 'common',
    icon: 'fa-star-half-stroke',
    label: 'Silver Player',
    labelTH: 'ผู้เล่นระดับ Silver',
    desc: 'Steady and dependable. The backbone of every good party.',
    descTH: 'มั่นคงและน่าเชื่อถือ กระดูกสันหลังของทุกปาร์ตี้',
    color: '#A8A9AD',
    bg: 'rgba(168,169,173,0.12)',
    border: 'rgba(168,169,173,0.35)',
  },
  bronze: {
    id: 'bronze',
    rarity: 'common',
    icon: 'fa-award',
    label: 'Bronze Player',
    labelTH: 'ผู้เล่นระดับ Bronze',
    desc: 'Just getting started, but already showing real promise.',
    descTH: 'เพิ่งเริ่มต้นแต่มีแววที่ดีอยู่แล้ว',
    color: '#CD7F32',
    bg: 'rgba(205,127,50,0.12)',
    border: 'rgba(205,127,50,0.30)',
  },
  sadness: {
    id: 'sadness',
    rarity: 'common',
    icon: 'fa-cloud-rain',
    label: 'Sadness',
    labelTH: 'ผู้เล่นเศร้า',
    desc: 'Had the worst luck imaginable. Impossibly, cosmically unlucky.',
    descTH: 'โชคร้ายที่สุดเท่าที่จะเป็นไปได้ในจักรวาล',
    color: '#6B7280',
    bg: 'rgba(107,114,128,0.12)',
    border: 'rgba(107,114,128,0.30)',
  },
  charity: {
    id: 'charity',
    rarity: 'common',
    icon: 'fa-heart',
    label: 'Charity Chairman',
    labelTH: 'ประธานสมาคมการกุศล',
    desc: 'Big heart, bigger soul. Always looking out for everyone else.',
    descTH: 'ใจใหญ่และมีน้ำใจ มักคอยดูแลคนอื่นเสมอ',
    color: '#DB2777',
    bg: 'rgba(219,39,119,0.12)',
    border: 'rgba(219,39,119,0.30)',
  },
}

const RARITY_ORDER = ['legendary', 'epic', 'rare', 'common']

export const ACHIEVEMENT_LIST = Object.values(ACHIEVEMENTS).sort(
  (a, b) => RARITY_ORDER.indexOf(a.rarity) - RARITY_ORDER.indexOf(b.rarity)
)

export const ACHIEVEMENTS_BY_RARITY = RARITY_ORDER.map(r => ({
  rarity: RARITY[r],
  items: ACHIEVEMENT_LIST.filter(a => a.rarity === r),
}))
