export const translations = {
  th: {
    nav: {
      home: 'หน้าแรก',
      scripts: 'สคริปต์',
      party: 'ปาร์ตี้',
      login: 'LINE Login',
      myParty: 'ปาร์ตี้ของฉัน',
      logout: 'ออกจากระบบ',
      lineMember: 'LINE Member',
    },
    home: {
      eyebrow: 'Murder Mystery · Role Play · Detective',
      partiesOpen: 'ปาร์ตี้เปิดอยู่',
      viewScripts: 'ดูสคริปต์ทั้งหมด',
      aboutUs: 'เกี่ยวกับเรา',
      brandEyebrow: 'Sofun Club Thailand',
      brandHeading: 'ต้นกำเนิดของ script murder',
      brandDesc: 'ต้นกําเนิดของเกม script murder เป็นที่นิยมมากในประเทศแถบยุโรปและอเมริกา เรื่องราวการฆาตกรรมเสมือนจริงถูกสร้างขึ้นโดยใช้สคริปต์ และผู้เล่นจะไขคดีผ่านการอ่านเนื้อเรื่องและการให้เหตุผลเพื่อค้นหาฆาตกร ต่อมาเกมถูกดัดแปลงและอัปเกรดในประเทศจีนให้กลายเป็นเกม script murder ที่เรารู้จักในปัจจุบัน',
      discoverStory: 'ค้นพบเรื่องราวของเรา →',
      statScripts: 'สคริปต์ในระบบ',
      statMembers: 'มาชิกของ Sofun',
      statFirst: 'Script Murder Platform เจ้าแรกในไทย',
      howEyebrow2: 'รู้จัก Script Murder',
      howHeading2: 'เกมสืบสวนสวมบทบาท',
      howF1: 'คุณสามารถเห็นสิ่งที่ตัวละครเห็นผ่านสายตาของตัวละคร คิดสิ่งที่พวกเขาคิดด้วยจิตวิญญาณของตัวละคร และตัวเลือกของคุณจะกำหนดชะตากรรมของพวกเขา',
      howF2: 'เราขอนำเสนอเครื่องแต่งกายที่งดงาม ฉากที่สวยงาม และเนื้อเรื่องที่เข้มข้น แสดงให้เห็นถึง ความสุข ความรัก ความเศร้า ไปจนถึงความกลัว!',
      howF3: 'ตั้งแต่เกิด เราทุกคนกระหายที่จะไล่ตามความจริง เราปกปิดความลับของเรา ใช้การสังเกตและการสอบสวนเพื่อเปิดเผยความลับของผู้อื่น แล้วฟื้นฟูความจริงของสิ่งต่าง ๆ อย่างสมบูรณ์แบบ!',
      howF4: 'ทุก ๆ ตัวละครมีภูมิหลังหรือความลับเป็นของตัวเอง ดังนั้นจะไม่สามารถมีผู้เล่นที่มากกว่าหรือน้อยกว่าตามที่เกมกำหนดได้',
      howF5: 'ไม่ต้องกังวล พวกเรามี DM หรือผู้ดำเนินเกมที่เชี่ยวชาญ จะคอยช่วยเหลือคุณอยู่ตลอดทั้งการเล่นเกม',
      specGameType: 'ประเภทเกม',
      specPlayers: 'จำนวนผู้เล่น',
      specPlayers2: '2–12 คน',
      specDuration: 'ระยะเวลา',
      specDuration2: '3-8 ชั่วโมง',
      specDifficulty: 'ระดับความยาก',
      specDifficulty2: '4 ระดับ',
      specCategories: 'หมวดหมู่หลัก:',
      specCat1: 'สืบสวน',
      specCat2: 'สยองขวัญ',
      specCat3: 'ดราม่า',
      specCat4: 'คอมแมนดี้',
      promoEyebrow: 'โปรโมชั่นประจำเดือน',
      promoMonth: 'มิถุนายน 2025',
      promoDesc: 'โปรโมชั่นสำหรับผู้ที่สมัครเป็นสมาชิกร้าน',
      viewScriptsMonth: 'ดูสคริปต์เดือนนี้',
      register: 'สมัครสมาชิก',
      howEyebrow: 'รู้จัก Script Murder',
      howHeading: 'เกมสืบสวนสวมบทบาท',
      partyEyebrow: 'ปาร์ตี้เปิดรับสมาชิก',
      partyHeading: 'รวมทีม เล่นด้วยกัน',
      createParty: 'สร้างปาร์ตี้',
      viewAll: 'ดูทั้งหมด →',
      noParty: 'ยังไม่มีปาร์ตี้ที่เปิดรับสมาชิกขณะนี้',
      firstParty: 'สร้างปาร์ตี้แรก',
      join: 'ขอเข้าร่วม',
      joined: 'เข้าร่วมแล้ว',
      pending: 'รออนุมัติ',
      mine: 'ของฉัน',
      full: 'เต็ม',
      seatFull: 'ที่นั่งเต็ม',
      videoEyebrow: 'วิดีโอประจำเดือน',
      videoHeading: 'สคริปต์ใหม่',
      videoDesc: 'ติดตามสคริปต์ใหม่และกิจกรรมพิเศษประจำเดือน อัพเดทใหม่ทุกเดือน',
      scriptsEyebrow: 'สคริปต์แนะนำ',
      scriptsHeading: 'เลือกเล่นในแบบที่คุณชอบ',
      viewAllScripts: 'ดูทั้งหมด →',
      teamEyebrow: 'ทีมงาน SoFun',
      teamHeading: 'พบกับทีมสร้างสรรค์ผู้อยู่เบื้องหลัง',
      teamSub: 'ทีมงานผู้เชี่ยวชาญที่หลงใหลในโลกของ Script Murder และความบันเทิงเชิงสร้างสรรค์',
      contactTeam: 'ติดต่อทีมงาน →',
      ctaHeading: 'เชื่อมต่อกับเรา',
      ctaSub: 'ทีมงานพร้อมให้ข้อมูลและช่วยเลือกสคริปต์ที่เหมาะกับกลุ่มของคุณ',
      ctaBtn: 'ดูสคริปต์ทั้งหมด →',
      free: 'ฟรี',
      findParty: 'หาปาร์ตี้',
      statScriptLabel: 'สคริปต์',
      statMemberLabel: 'สมาชิก',
      statYearsLabel: 'ปีประสบการณ์',
      heroBeginner: 'มือใหม่',
      heroBeginnerSub: 'ง่าย–ปานกลาง',
      heroAdvanced: 'ขั้นสูง',
      heroAdvancedSub: 'ยาก–ยากมาก',
      heroPartySub: 'เปิดรับสมาชิก',
      catalogEyebrow: 'คลังสคริปต์',
      catalogHeading: 'เลือกสคริปต์ของคุณ',
      openAllFiles: 'เปิดแฟ้มคดีทั้งหมด',
      feat1Title: 'สวมบทบาทจริง',
      feat1Desc: 'แต่ละคนรับบทละครเฉพาะตนพร้อมความลับที่ต้องปกปิด',
      feat2Title: 'สืบสวนร่วมกัน',
      feat2Desc: 'ตั้งคำถาม หาเบาะแส เปิดเผยเรื่องราวสดกับเพื่อน',
      feat3Title: 'เรื่องราวหลากหลาย',
      feat3Desc: 'Horror, Drama, Detective — กว่า 48 เรื่องให้เลือกเล่น',
      statsPride: 'ตัวเลขที่ภูมิใจ',
      statReadySub: 'พร้อมเล่นในคลัง',
      statDetective: 'นักสืบ',
      statActiveSub: 'สมาชิกที่ใช้งาน',
      statStarting: 'เริ่มต้น',
      statPriceSub: 'ราคาต่อคนต่อเกม',
      statYears: 'ปี',
      statExpSub: 'ประสบการณ์',
      statsClaim: 'ประสบการณ์ Script Murder ที่ดีที่สุดในประเทศไทย — เล่นได้ทันที ไม่ต้องรอ',
      chooseScript: 'เลือกสคริปต์ →',
      howStartEyebrow: 'วิธีเริ่มต้น',
      howStartHeading: 'เริ่มต้นใน 3 ขั้นตอน',
      step1Title: 'เลือกสคริปต์',
      step1Desc: 'เลือกเรื่องราวจากแฟ้มคดีกว่า 48 เรื่อง กรองตามจำนวนผู้เล่นและระดับความยาก',
      step2Title: 'ชวนเพื่อน',
      step2Desc: 'แชร์ให้เพื่อนในกลุ่ม แต่ละคนรับบทละครและอ่านรายละเอียดเฉพาะตน',
      step3Title: 'ไขปริศนา',
      step3Desc: 'ตั้งโต๊ะ ตั้งคำถาม หาเบาะแส และค้นหาว่าใครคือฆาตกรก่อนหมดเวลา',
      startPlaying: 'เริ่มเล่นเลย →',
      joinParty: 'เข้าร่วม',
      footerReadyEyebrow: 'พร้อมแล้ว?',
      footerReadyHeading: 'พร้อมจะไขคดีหรือยัง?',
      footerDesc: 'เริ่มต้นง่าย เลือกสคริปต์ที่ชอบ ชวนเพื่อนมาสืบสวน และค้นหาว่าใครคือฆาตกร',
      registerLine: 'สมัครสมาชิก LINE',
      footerTagline: 'แพลตฟอร์ม Script Murder สัญชาติไทย สำหรับสายสืบสวนและนักเล่นเกม',
      footerScripts: 'สคริปต์',
      footerCommunity: 'ชุมชน',
      footerInfo: 'ข้อมูล',
      footerAllScripts: 'สคริปต์ทั้งหมด',
      footerFreeScripts: 'สคริปต์ฟรี',
      footerNewScripts: 'สคริปต์ใหม่',
      footerFeaturedScripts: 'สคริปต์แนะนำ',
      footerOpenParty: 'ปาร์ตี้เปิดรับ',
      footerCreateParty: 'สร้างปาร์ตี้',
      footerMyProfile: 'โปรไฟล์ของฉัน',
      footerContact: 'ติดต่อเรา',
      playerCount: 'คน',
    },
    games: {
      searchPlaceholder: 'ค้นหาชื่อสคริปต์...',
      filters: 'ตัวกรอง',
      clearAll: 'ล้างทั้งหมด',
      genre: 'แนวเกม',
      difficulty: 'ความยาก',
      players: 'จำนวนผู้เล่น',
      detectiveLevel: 'ระดับสืบ (ขั้นต่ำ)',
      roleplayLevel: 'ระดับสวมบทบาท (ขั้นต่ำ)',
      scripts: 'สคริปต์',
      clearFilter: 'ล้างตัวกรอง',
      notFound: 'ไม่พบสคริปต์ที่ค้นหา',
      detective: 'สืบ',
      roleplay: 'บท',
      free: 'ฟรี',
      perPerson: '฿/คน',
      clickDetail: 'คลิกเพื่อดูรายละเอียด →',
      synopsis: 'เนื้อเรื่องย่อ',
      readMore: 'อ่านเพิ่มเติม →',
      playerCount: 'คน',
    },
    party: { title: 'จัดปาร์ตี้' },
    profile: {
      title: 'โปรไฟล์',
      personalInfo: 'ข้อมูลส่วนตัว',
      firstname: 'ชื่อจริง',
      lastname: 'นามสกุล',
      nickname: 'ชื่อเล่น',
      phone: 'เบอร์โทรศัพท์',
      email: 'อีเมล',
      birthday: 'วันเกิด',
      gender: 'เพศ',
      genderMale: 'ชาย',
      genderFemale: 'หญิง',
      genderOther: 'อื่นๆ',
      save: 'บันทึกข้อมูล',
      saving: 'กำลังบันทึก...',
      saved: 'บันทึกแล้ว!',
      account: 'บัญชี',
      connected: 'เชื่อมต่อแล้ว',
      logout: 'ออกจากระบบ',
      notLoggedIn: 'ยังไม่ได้เข้าสู่ระบบ',
      loginPrompt: 'เข้าสู่ระบบด้วย LINE เพื่อดูและแก้ไขโปรไฟล์ของคุณ',
      lineMember: 'LINE Member',
      admin: 'Admin',
    },
  },

  en: {
    nav: {
      home: 'Home',
      scripts: 'Scripts',
      party: 'Party',
      login: 'LINE Login',
      myParty: 'My Party',
      logout: 'Logout',
      lineMember: 'LINE Member',
    },
    home: {
      eyebrow: 'Murder Mystery · Role Play · Detective',
      partiesOpen: 'parties open',
      viewScripts: 'View All Scripts',
      aboutUs: 'About Us',
      brandEyebrow: 'Sofun Club Thailand',
      brandHeading: 'The Origin of Script Murder',
      brandDesc: 'Script murder games are highly popular in Europe and America. Fictional murder stories are created using scripts, and players solve cases by reading the story and reasoning to find the killer. The game was later adapted and upgraded in China into the script murder game we know today.',
      discoverStory: 'Discover Our Story →',
      statScripts: 'Scripts Available',
      statMembers: 'Sofun Members',
      statFirst: "Thailand's #1 Script Murder Platform",
      howEyebrow2: 'About Script Murder',
      howHeading2: 'Detective Role-Play Game',
      howF1: 'You can see what the characters see through their eyes, think what they think with the spirit of the character, and your choices will determine their fate.',
      howF2: 'We offer beautiful costumes, stunning scenes, and intense storylines showcasing happiness, love, sorrow, and fear!',
      howF3: 'From birth, we all crave the truth. We hide our secrets and use observation and investigation to reveal the secrets of others, restoring the truth perfectly!',
      howF4: 'Every character has their own background and secrets, so the number of players cannot exceed or fall short of what the game requires.',
      howF5: "Don't worry — we have an expert DM or game master who will guide and assist you throughout the entire game.",
      specGameType: 'Game Type',
      specPlayers: 'Players',
      specPlayers2: '2–12 players',
      specDuration: 'Duration',
      specDuration2: '3–8 hours',
      specDifficulty: 'Difficulty',
      specDifficulty2: '4 levels',
      specCategories: 'Main Genres:',
      specCat1: 'Detective',
      specCat2: 'Horror',
      specCat3: 'Drama',
      specCat4: 'Comedy',
      promoEyebrow: 'Monthly Promotion',
      promoMonth: 'June 2025',
      promoDesc: 'Special promotions for our registered members',
      viewScriptsMonth: "This Month's Scripts",
      register: 'Register',
      howEyebrow: 'About Script Murder',
      howHeading: 'Detective Role-Play Game',
      partyEyebrow: 'Open Parties',
      partyHeading: 'Team Up & Play Together',
      createParty: 'Create Party',
      viewAll: 'View All →',
      noParty: 'No open parties at the moment',
      firstParty: 'Create First Party',
      join: 'Request to Join',
      joined: 'Joined',
      pending: 'Pending',
      mine: 'Mine',
      full: 'Full',
      seatFull: 'Full',
      videoEyebrow: 'Monthly Video',
      videoHeading: 'New Scripts',
      videoDesc: 'Follow new scripts and special monthly events. Updated every month.',
      scriptsEyebrow: 'Featured Scripts',
      scriptsHeading: 'Play the Way You Like',
      viewAllScripts: 'View All →',
      teamEyebrow: 'SoFun Team',
      teamHeading: 'Meet the Creative Team Behind It All',
      teamSub: 'A team of passionate experts in the world of Script Murder and creative entertainment',
      contactTeam: 'Contact Our Team →',
      ctaHeading: 'Connect With Us',
      ctaSub: 'Our team is ready to help you choose the right script for your group',
      ctaBtn: 'View All Scripts →',
      free: 'Free',
      findParty: 'Find Party',
      statScriptLabel: 'Scripts',
      statMemberLabel: 'Members',
      statYearsLabel: 'Yrs Experience',
      heroBeginner: 'Beginner',
      heroBeginnerSub: 'Easy–Normal',
      heroAdvanced: 'Advanced',
      heroAdvancedSub: 'Hard–Expert',
      heroPartySub: 'Open for members',
      catalogEyebrow: 'Script Library',
      catalogHeading: 'Choose Your Script',
      openAllFiles: 'Open All Case Files',
      feat1Title: 'Real Role-Play',
      feat1Desc: 'Each player receives a unique character role with secrets to keep',
      feat2Title: 'Investigate Together',
      feat2Desc: 'Ask questions, find clues, and uncover the story live with friends',
      feat3Title: 'Diverse Stories',
      feat3Desc: 'Horror, Drama, Detective — over 48 stories to choose from',
      statsPride: 'Our Numbers',
      statReadySub: 'Ready in Library',
      statDetective: 'Detectives',
      statActiveSub: 'Active Members',
      statStarting: 'Starting',
      statPriceSub: 'Per person per game',
      statYears: 'Yrs',
      statExpSub: 'Experience',
      statsClaim: "Thailand's best Script Murder experience — play instantly, no waiting",
      chooseScript: 'Choose Script →',
      howStartEyebrow: 'How to Start',
      howStartHeading: '3 Steps to Start',
      step1Title: 'Choose Script',
      step1Desc: 'Choose from over 48 case files, filtered by player count and difficulty level',
      step2Title: 'Invite Friends',
      step2Desc: 'Share with your group. Each player receives their own character role and private details.',
      step3Title: 'Solve the Mystery',
      step3Desc: 'Set up, ask questions, find clues, and discover who the killer is before time runs out.',
      startPlaying: 'Start Playing →',
      joinParty: 'Join',
      footerReadyEyebrow: 'Ready?',
      footerReadyHeading: 'Ready to Solve the Case?',
      footerDesc: 'Get started easily — choose your script, invite friends to investigate, and find the killer.',
      registerLine: 'Register with LINE',
      footerTagline: "Thailand's Script Murder platform for investigators and game enthusiasts",
      footerScripts: 'Scripts',
      footerCommunity: 'Community',
      footerInfo: 'Info',
      footerAllScripts: 'All Scripts',
      footerFreeScripts: 'Free Scripts',
      footerNewScripts: 'New Scripts',
      footerFeaturedScripts: 'Featured Scripts',
      footerOpenParty: 'Open Parties',
      footerCreateParty: 'Create Party',
      footerMyProfile: 'My Profile',
      footerContact: 'Contact Us',
      playerCount: 'players',
    },
    games: {
      searchPlaceholder: 'Search scripts...',
      filters: 'Filters',
      clearAll: 'Clear All',
      genre: 'Genre',
      difficulty: 'Difficulty',
      players: 'Players',
      detectiveLevel: 'Detective Level (Min)',
      roleplayLevel: 'Roleplay Level (Min)',
      scripts: 'Scripts',
      clearFilter: 'Clear Filters',
      notFound: 'No scripts found',
      detective: 'Det.',
      roleplay: 'Role',
      free: 'Free',
      perPerson: '฿/person',
      clickDetail: 'Click for details →',
      synopsis: 'Synopsis',
      readMore: 'Read more →',
      playerCount: 'players',
    },
    party: { title: 'Party' },
    profile: {
      title: 'Profile',
      personalInfo: 'Personal Information',
      firstname: 'First Name',
      lastname: 'Last Name',
      nickname: 'Nickname',
      phone: 'Phone Number',
      email: 'Email',
      birthday: 'Birthday',
      gender: 'Gender',
      genderMale: 'Male',
      genderFemale: 'Female',
      genderOther: 'Other',
      save: 'Save',
      saving: 'Saving...',
      saved: 'Saved!',
      account: 'Account',
      connected: 'Connected',
      logout: 'Logout',
      notLoggedIn: 'Not Logged In',
      loginPrompt: 'Sign in with LINE to view and edit your profile',
      lineMember: 'LINE Member',
      admin: 'Admin',
    },
  },

  zh: {
    nav: {
      home: '首页',
      scripts: '剧本',
      party: '派对',
      login: 'LINE 登录',
      myParty: '我的派对',
      logout: '退出登录',
      lineMember: 'LINE 会员',
    },
    home: {
      eyebrow: '谋杀之谜 · 角色扮演 · 侦探',
      partiesOpen: '个派对开放中',
      viewScripts: '查看所有剧本',
      aboutUs: '关于我们',
      brandEyebrow: 'Sofun Club Thailand',
      brandHeading: '剧本杀的起源',
      brandDesc: '剧本杀游戏在欧美地区极为流行。虚构的谋杀故事通过剧本呈现，玩家通过阅读故事情节和逻辑推理来找出凶手。该游戏后来在中国经过改良和升级，成为了我们今天所熟知的剧本杀游戏。',
      discoverStory: '了解我们的故事 →',
      statScripts: '剧本总数',
      statMembers: 'Sofun 会员',
      statFirst: '泰国首家剧本杀平台',
      howEyebrow2: '了解剧本杀',
      howHeading2: '侦探角色扮演游戏',
      howF1: '你可以透过角色的眼睛看到他们所见，用角色的灵魂思考他们所想，而你的选择将决定他们的命运。',
      howF2: '我们为您提供精美服装、华丽场景和紧凑剧情，展现喜悦、爱情、悲伤乃至恐惧的真实情感！',
      howF3: '从出生起，我们都渴望追寻真相。我们隐藏自己的秘密，通过观察与调查揭露他人的秘密，最终完美还原事实真相！',
      howF4: '每个角色都有属于自己的背景和秘密，因此玩家人数不能超过或少于游戏所规定的人数。',
      howF5: '不用担心，我们有专业的DM（游戏主持人）全程陪伴指导您完成整个游戏。',
      specGameType: '游戏类型',
      specPlayers: '玩家人数',
      specPlayers2: '2–12 人',
      specDuration: '游戏时长',
      specDuration2: '3–8 小时',
      specDifficulty: '难度等级',
      specDifficulty2: '4 个等级',
      specCategories: '主要类型：',
      specCat1: '悬疑推理',
      specCat2: '恐怖惊悚',
      specCat3: '情感剧情',
      specCat4: '欢乐喜剧',
      promoEyebrow: '本月活动',
      promoMonth: '2025年6月',
      promoDesc: '为注册会员提供的专属优惠活动',
      viewScriptsMonth: '查看本月剧本',
      register: '注册会员',
      howEyebrow: '了解剧本杀',
      howHeading: '侦探角色扮演游戏',
      partyEyebrow: '开放派对',
      partyHeading: '组队一起玩',
      createParty: '创建派对',
      viewAll: '查看全部 →',
      noParty: '目前暂无开放中的派对',
      firstParty: '创建第一个派对',
      join: '申请加入',
      joined: '已加入',
      pending: '待审批',
      mine: '我的',
      full: '已满',
      seatFull: '座位已满',
      videoEyebrow: '本月视频',
      videoHeading: '全新剧本',
      videoDesc: '关注每月新剧本和特别活动，每月更新。',
      scriptsEyebrow: '精选剧本',
      scriptsHeading: '按您喜欢的方式畅玩',
      viewAllScripts: '查看全部 →',
      teamEyebrow: 'SoFun 团队',
      teamHeading: '认识幕后创作团队',
      teamSub: '一群热爱剧本杀与创意娱乐的专业团队',
      contactTeam: '联系我们的团队 →',
      ctaHeading: '与我们联系',
      ctaSub: '我们的团队随时准备为您提供信息，并帮您选择适合您团队的剧本',
      ctaBtn: '查看所有剧本 →',
      free: '免费',
      findParty: '寻找派对',
      statScriptLabel: '剧本',
      statMemberLabel: '会员',
      statYearsLabel: '年经验',
      heroBeginner: '新手',
      heroBeginnerSub: '简单–普通',
      heroAdvanced: '进阶',
      heroAdvancedSub: '困难–超难',
      heroPartySub: '招募中',
      catalogEyebrow: '剧本库',
      catalogHeading: '选择您的剧本',
      openAllFiles: '查看所有案件档案',
      feat1Title: '真实角色扮演',
      feat1Desc: '每位玩家都有独特角色，有秘密需要保守',
      feat2Title: '共同调查',
      feat2Desc: '提问、寻找线索、与朋友共同揭开故事',
      feat3Title: '多样故事',
      feat3Desc: 'Horror、Drama、Detective——超过48个故事可选',
      statsPride: '我们的数字',
      statReadySub: '可立即游玩',
      statDetective: '侦探',
      statActiveSub: '活跃会员',
      statStarting: '起价',
      statPriceSub: '每人每局',
      statYears: '年',
      statExpSub: '经验',
      statsClaim: '泰国最佳剧本杀体验——即刻开玩，无需等待',
      chooseScript: '选择剧本 →',
      howStartEyebrow: '如何开始',
      howStartHeading: '3步开始',
      step1Title: '选择剧本',
      step1Desc: '从超过48个案件档案中选择，按玩家人数和难度筛选',
      step2Title: '邀请朋友',
      step2Desc: '与群组分享，每位玩家收到自己的角色和专属详情',
      step3Title: '解开谜题',
      step3Desc: '就位、提问、寻找线索，在时间用完前找出凶手',
      startPlaying: '立即开始 →',
      joinParty: '加入',
      footerReadyEyebrow: '准备好了？',
      footerReadyHeading: '准备破案了吗？',
      footerDesc: '轻松开始——选择剧本，邀请朋友调查，找出凶手',
      registerLine: 'LINE 注册',
      footerTagline: '泰国剧本杀平台，为侦探爱好者和游戏玩家而生',
      footerScripts: '剧本',
      footerCommunity: '社区',
      footerInfo: '信息',
      footerAllScripts: '全部剧本',
      footerFreeScripts: '免费剧本',
      footerNewScripts: '新剧本',
      footerFeaturedScripts: '精选剧本',
      footerOpenParty: '开放派对',
      footerCreateParty: '创建派对',
      footerMyProfile: '我的资料',
      footerContact: '联系我们',
      playerCount: '人',
    },
    games: {
      searchPlaceholder: '搜索剧本名称...',
      filters: '筛选',
      clearAll: '清除全部',
      genre: '游戏类型',
      difficulty: '难度',
      players: '玩家人数',
      detectiveLevel: '推理等级（最低）',
      roleplayLevel: '角色扮演等级（最低）',
      scripts: '个剧本',
      clearFilter: '清除筛选',
      notFound: '未找到相关剧本',
      detective: '推理',
      roleplay: '角色',
      free: '免费',
      perPerson: '฿/人',
      clickDetail: '点击查看详情 →',
      synopsis: '剧情简介',
      readMore: '阅读更多 →',
      playerCount: '人',
    },
    party: { title: '派对' },
    profile: {
      title: '个人资料',
      personalInfo: '个人信息',
      firstname: '名字',
      lastname: '姓氏',
      nickname: '昵称',
      phone: '电话号码',
      email: '电子邮件',
      birthday: '生日',
      gender: '性别',
      genderMale: '男',
      genderFemale: '女',
      genderOther: '其他',
      save: '保存',
      saving: '保存中...',
      saved: '已保存！',
      account: '账户',
      connected: '已连接',
      logout: '退出登录',
      notLoggedIn: '尚未登录',
      loginPrompt: '使用 LINE 登录以查看和编辑您的个人资料',
      lineMember: 'LINE 会员',
      admin: '管理员',
    },
  },
}

export function getT(lang) {
  const dict = translations[lang] || translations.th
  return (section, key) => dict[section]?.[key] ?? translations.th[section]?.[key] ?? key
}
